name: MultiTools
version: 0.0.1-SNAPSHOT
main: com.thedreamsanctuary.multitools.MultiTools
author: ShiniOfTheGami
authors: [DukeVindzor, AceDexter]

commands:
   multitool:
     description: Manage MultiTools
     aliases: [mt, tools]
     usage: |
      USAGE:
      /multitools range - Toggles long range for tools
      /multitools all - Toggles editing for all blocks or just solids
      /multitools list - Prints list of all tools available
      /multitools get <tool>|all - Gives you the specified tool

permissions:
   multitools.commands.*:
     description: Gives access to all MultiTools features
     children:
       multitools.togglerange: true
       multitools.list: true
       multitools.get.*: true
   multitools.command.get.*:
     description: Allows player to spawn all tools
     children:
       multitools.get.jackhammer: true
       multitools.get.paintbrush: true
       multitools.get.datawrench: true
       multitools.get.sledgehammer: true
       multitools.get.duplicator: true
   multitools.command.get.jackhammer:
     description: Allows player to spawn Jackhammer
     default: op
   multitools.command.get.paintbrush:
     description: Allows player to spawn Paint Brush
     default: op
   multitools.command.get.datawrench:
     description: Allows player to spawn Data Wrench
     default: op
   multitools.command.get.sledgehammer:
     description: Allows player to spawn Sledgehammer
     default: op
   multitools.command.get.duplicator:
     description: Allows player to spawn Duplicator
     default: op
   multitools.command.list:
     description: Prints list of all tools available
     default: op
   multitools.command.togglerange:
     description: Toggles long range for tools
     default: op
   multitools.command.toggleall:
     description: Toggles editing of all blocks for tools
     default: op